# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      # run: ls && ant -noinput -buildfile build.xml
      run: ls && ant clean && ant
    - name: copy file tomcat to root folder
      run: cp /home/runner/work/demo/demo/apache-tomcat-9.0.37/webapps/ROOT.war ROOT.war
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v2
      with:
        path: ROOT.war
    # - name: install ssh
    #   run: sudo apt-get update && sudo apt-get -y install openssh-client && sudo apt-get -y install sshpass
    # - name: login ssh
    #   run: sshpass -p vino@2020 ssh -o "StrictHostKeyChecking no" -P root@82.196.6.114 "ls"
    # - name: copy
    #   run: cd /home/runner/work/demo/demo/apache-tomcat-9.0.37/webapps/ && ls && sshpass -V && export SSHPASS=vino@2020 && sshpass -e scp -o stricthostkeychecking=no /home/runner/work/demo/demo/ROOT.war root@82.196.6.114:/root
    # - name: check
    #   run: sshpass -p vino@2020 ssh -o "StrictHostKeyChecking no" -P root@82.196.6.114 "ls"

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    # - name: install ssh
    #   run: sudo apt-get update && sudo apt-get -y install openssh-client && sudo apt-get -y install sshpass
    # - name: login ssh
    #   run: sshpass -p vino@2020 ssh -o "StrictHostKeyChecking no" -P root@82.196.6.114 "ls"
    - name: copy
      run: ls
    #   run: ls && cd /home/runner/work/demo/demo/apache-tomcat-9.0.37/webapps/ && ls && sshpass -V && export SSHPASS=vino@2020 && sshpass -e scp -o stricthostkeychecking=no /home/runner/work/demo/demo/ROOT1.war root@82.196.6.114:/root
    # - name: check
    #   run: sshpass -p vino@2020 ssh -o "StrictHostKeyChecking no" -P root@82.196.6.114 "ls"
